
---

- name: ping testing
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:

    # test reachability to 8.8.8.8 using mgmt vrf
  - nxos_ping: dest=8.8.8.8 vrf=management host={{ inventory_hostname }}

    # Test reachability to a few different public IPs using mgmt vrf
    # if device has name lookups turned on, you can use names
    - nxos_ping: dest={{ item }} vrf=management host={{ inventory_hostname }}
      loop:
        - 8.8.8.8
        - 10.1.150.1